### ISSUE TITLE
Page-wrapper displacement

### ISSUE THREAD

**Issue by limarkdl-private** [limarkdl-private/frontend-main-practice-own#2]
Suspicious x-shift happens when I change pages from Main to About, like only a few pixels, but still

**Comment by limarkdl** [comment]
The reason was the lack of overflow: scroll. Since there was not enough content on the Main page, the scrollbar did not appear, which caused the text to automatically shift to the right. Now overflow-y will always scroll, so that even with a lack of content, there will still be a plate.
